import torch
import torch.nn as nn
from torch.autograd import Variable
from functools import reduce
import math
import torch.nn.functional as F
class LambdaBase(nn.Sequential):
    def __init__(self, fn, *args):
        super(LambdaBase, self).__init__(*args)
        self.lambda_func = fn

    def forward_prepare(self, input):
        output = []
        for module in self._modules.values():
            output.append(module(input))
        return output if output else input

class Lambda(LambdaBase):
    def forward(self, input):
        return self.lambda_func(self.forward_prepare(input))

class LambdaMap(LambdaBase):
    def forward(self, input):
        return list(map(self.lambda_func,self.forward_prepare(input)))

class LambdaReduce(LambdaBase):
    def forward(self, input):
        return reduce(self.lambda_func,self.forward_prepare(input))
    
class SamePad2d(nn.Module):
    """Mimics tensorflow's 'SAME' padding.
    """

    def __init__(self, kernel_size, stride):
        super(SamePad2d, self).__init__()
        self.kernel_size = torch.nn.modules.utils._pair(kernel_size)
        self.stride = torch.nn.modules.utils._pair(stride)

    def forward(self, input):
        in_width = input.size()[2]
        in_height = input.size()[3]
        out_width = math.ceil(float(in_width) / float(self.stride[0]))
        out_height = math.ceil(float(in_height) / float(self.stride[1]))
        pad_along_width = ((out_width - 1) * self.stride[0] +
                           self.kernel_size[0] - in_width)
        pad_along_height = ((out_height - 1) * self.stride[1] +
                            self.kernel_size[1] - in_height)
        pad_left = math.floor(pad_along_width / 2)
        pad_top = math.floor(pad_along_height / 2)
        pad_right = pad_along_width - pad_left
        pad_bottom = pad_along_height - pad_top
        return F.pad(input, (pad_left, pad_right, pad_top, pad_bottom), 'constant', 0)

    def __repr__(self):
        return self.__class__.__name__

class ResNext(nn.Module):
    def __init__(self, stage5=True):
        super(ResNext, self).__init__()
        self.stage5 = stage5
        
        self.C1 = nn.Sequential(
            nn.Conv2d(3,64,(7, 7),(2, 2),(3, 3),1,1,bias=False),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            # SamePad2d(kernel_size=3, stride=2),
            nn.MaxPool2d((3, 3),(2, 2),(1, 1)),
        )
        
        self.C2 = nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        LambdaMap(lambda x: x, # ConcatTable,
                            nn.Sequential( # Sequential,
                                nn.Sequential( # Sequential,
                                    nn.Conv2d(64,128,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                    nn.BatchNorm2d(128),
                                    nn.ReLU(),
                                    nn.Conv2d(128,128,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                                    nn.BatchNorm2d(128),
                                    nn.ReLU(),
                                ),
                                nn.Conv2d(128,256,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                nn.BatchNorm2d(256),
                            ),
                            nn.Sequential( # Sequential,
                                nn.Conv2d(64,256,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                nn.BatchNorm2d(256),
                            ),
                        ),
                        LambdaReduce(lambda x,y: x+y), # CAddTable,
                        nn.ReLU(),
                    ),
                    nn.Sequential( # Sequential,
                        LambdaMap(lambda x: x, # ConcatTable,
                            nn.Sequential( # Sequential,
                                nn.Sequential( # Sequential,
                                    nn.Conv2d(256,128,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                    nn.BatchNorm2d(128),
                                    nn.ReLU(),
                                    nn.Conv2d(128,128,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                                    nn.BatchNorm2d(128),
                                    nn.ReLU(),
                                ),
                                nn.Conv2d(128,256,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                nn.BatchNorm2d(256),
                            ),
                            Lambda(lambda x: x), # Identity,
                        ),
                        LambdaReduce(lambda x,y: x+y), # CAddTable,
                        nn.ReLU(),
                    ),
                    nn.Sequential( # Sequential,
                        LambdaMap(lambda x: x, # ConcatTable,
                            nn.Sequential( # Sequential,
                                nn.Sequential( # Sequential,
                                    nn.Conv2d(256,128,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                    nn.BatchNorm2d(128),
                                    nn.ReLU(),
                                    nn.Conv2d(128,128,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                                    nn.BatchNorm2d(128),
                                    nn.ReLU(),
                                ),
                                nn.Conv2d(128,256,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                nn.BatchNorm2d(256),
                            ),
                            Lambda(lambda x: x), # Identity,
                        ),
                        LambdaReduce(lambda x,y: x+y), # CAddTable,
                        nn.ReLU(),
                    ),
                )
        self.C3 =     nn.Sequential( # Sequential,
                        nn.Sequential( # Sequential,
                            LambdaMap(lambda x: x, # ConcatTable,
                                nn.Sequential( # Sequential,
                                    nn.Sequential( # Sequential,
                                        nn.Conv2d(256,256,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                        nn.BatchNorm2d(256),
                                        nn.ReLU(),
                                        nn.Conv2d(256,256,(3, 3),(2, 2),(1, 1),1,32,bias=False),
                                        nn.BatchNorm2d(256),
                                        nn.ReLU(),
                                    ),
                                    nn.Conv2d(256,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                    nn.BatchNorm2d(512),
                                ),
                                nn.Sequential( # Sequential,
                                    nn.Conv2d(256,512,(1, 1),(2, 2),(0, 0),1,1,bias=False),
                                    nn.BatchNorm2d(512),
                                ),
                            ),
                            LambdaReduce(lambda x,y: x+y), # CAddTable,
                            nn.ReLU(),
                        ),
                        nn.Sequential( # Sequential,
                            LambdaMap(lambda x: x, # ConcatTable,
                                nn.Sequential( # Sequential,
                                    nn.Sequential( # Sequential,
                                        nn.Conv2d(512,256,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                        nn.BatchNorm2d(256),
                                        nn.ReLU(),
                                        nn.Conv2d(256,256,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                                        nn.BatchNorm2d(256),
                                        nn.ReLU(),
                                    ),
                                    nn.Conv2d(256,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                    nn.BatchNorm2d(512),
                                ),
                                Lambda(lambda x: x), # Identity,
                            ),
                            LambdaReduce(lambda x,y: x+y), # CAddTable,
                            nn.ReLU(),
                        ),
                        nn.Sequential( # Sequential,
                            LambdaMap(lambda x: x, # ConcatTable,
                                nn.Sequential( # Sequential,
                                    nn.Sequential( # Sequential,
                                        nn.Conv2d(512,256,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                        nn.BatchNorm2d(256),
                                        nn.ReLU(),
                                        nn.Conv2d(256,256,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                                        nn.BatchNorm2d(256),
                                        nn.ReLU(),
                                    ),
                                    nn.Conv2d(256,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                    nn.BatchNorm2d(512),
                                ),
                                Lambda(lambda x: x), # Identity,
                            ),
                            LambdaReduce(lambda x,y: x+y), # CAddTable,
                            nn.ReLU(),
                        ),
                        nn.Sequential( # Sequential,
                            LambdaMap(lambda x: x, # ConcatTable,
                                nn.Sequential( # Sequential,
                                    nn.Sequential( # Sequential,
                                        nn.Conv2d(512,256,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                        nn.BatchNorm2d(256),
                                        nn.ReLU(),
                                        nn.Conv2d(256,256,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                                        nn.BatchNorm2d(256),
                                        nn.ReLU(),
                                    ),
                                    nn.Conv2d(256,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                    nn.BatchNorm2d(512),
                                ),
                                Lambda(lambda x: x), # Identity,
                            ),
                            LambdaReduce(lambda x,y: x+y), # CAddTable,
                            nn.ReLU(),
                        ),
                    )
        self.C4 = nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        LambdaMap(lambda x: x, # ConcatTable,
                            nn.Sequential( # Sequential,
                                nn.Sequential( # Sequential,
                                    nn.Conv2d(512,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                    nn.Conv2d(512,512,(3, 3),(2, 2),(1, 1),1,32,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                ),
                                nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                nn.BatchNorm2d(1024),
                            ),
                            nn.Sequential( # Sequential,
                                nn.Conv2d(512,1024,(1, 1),(2, 2),(0, 0),1,1,bias=False),
                                nn.BatchNorm2d(1024),
                            ),
                        ),
                        LambdaReduce(lambda x,y: x+y), # CAddTable,
                        nn.ReLU(),
                    ),
                    nn.Sequential( # Sequential,
                        LambdaMap(lambda x: x, # ConcatTable,
                            nn.Sequential( # Sequential,
                                nn.Sequential( # Sequential,
                                    nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                    nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                ),
                                nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                nn.BatchNorm2d(1024),
                            ),
                            Lambda(lambda x: x), # Identity,
                        ),
                        LambdaReduce(lambda x,y: x+y), # CAddTable,
                        nn.ReLU(),
                    ),
                    nn.Sequential( # Sequential,
                        LambdaMap(lambda x: x, # ConcatTable,
                            nn.Sequential( # Sequential,
                                nn.Sequential( # Sequential,
                                    nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                    nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                ),
                                nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                nn.BatchNorm2d(1024),
                            ),
                            Lambda(lambda x: x), # Identity,
                        ),
                        LambdaReduce(lambda x,y: x+y), # CAddTable,
                        nn.ReLU(),
                    ),
                    nn.Sequential( # Sequential,
                        LambdaMap(lambda x: x, # ConcatTable,
                            nn.Sequential( # Sequential,
                                nn.Sequential( # Sequential,
                                    nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                    nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                ),
                                nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                nn.BatchNorm2d(1024),
                            ),
                            Lambda(lambda x: x), # Identity,
                        ),
                        LambdaReduce(lambda x,y: x+y), # CAddTable,
                        nn.ReLU(),
                    ),
                    nn.Sequential( # Sequential,
                        LambdaMap(lambda x: x, # ConcatTable,
                            nn.Sequential( # Sequential,
                                nn.Sequential( # Sequential,
                                    nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                    nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                ),
                                nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                nn.BatchNorm2d(1024),
                            ),
                            Lambda(lambda x: x), # Identity,
                        ),
                        LambdaReduce(lambda x,y: x+y), # CAddTable,
                        nn.ReLU(),
                    ),
                    nn.Sequential( # Sequential,
                        LambdaMap(lambda x: x, # ConcatTable,
                            nn.Sequential( # Sequential,
                                nn.Sequential( # Sequential,
                                    nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                    nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                ),
                                nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                nn.BatchNorm2d(1024),
                            ),
                            Lambda(lambda x: x), # Identity,
                        ),
                        LambdaReduce(lambda x,y: x+y), # CAddTable,
                        nn.ReLU(),
                    ),
                    nn.Sequential( # Sequential,
                        LambdaMap(lambda x: x, # ConcatTable,
                            nn.Sequential( # Sequential,
                                nn.Sequential( # Sequential,
                                    nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                    nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                ),
                                nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                nn.BatchNorm2d(1024),
                            ),
                            Lambda(lambda x: x), # Identity,
                        ),
                        LambdaReduce(lambda x,y: x+y), # CAddTable,
                        nn.ReLU(),
                    ),
                    nn.Sequential( # Sequential,
                        LambdaMap(lambda x: x, # ConcatTable,
                            nn.Sequential( # Sequential,
                                nn.Sequential( # Sequential,
                                    nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                    nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                ),
                                nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                nn.BatchNorm2d(1024),
                            ),
                            Lambda(lambda x: x), # Identity,
                        ),
                        LambdaReduce(lambda x,y: x+y), # CAddTable,
                        nn.ReLU(),
                    ),
                    nn.Sequential( # Sequential,
                        LambdaMap(lambda x: x, # ConcatTable,
                            nn.Sequential( # Sequential,
                                nn.Sequential( # Sequential,
                                    nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                    nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                ),
                                nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                nn.BatchNorm2d(1024),
                            ),
                            Lambda(lambda x: x), # Identity,
                        ),
                        LambdaReduce(lambda x,y: x+y), # CAddTable,
                        nn.ReLU(),
                    ),
                    nn.Sequential( # Sequential,
                        LambdaMap(lambda x: x, # ConcatTable,
                            nn.Sequential( # Sequential,
                                nn.Sequential( # Sequential,
                                    nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                    nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                ),
                                nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                nn.BatchNorm2d(1024),
                            ),
                            Lambda(lambda x: x), # Identity,
                        ),
                        LambdaReduce(lambda x,y: x+y), # CAddTable,
                        nn.ReLU(),
                    ),
                    nn.Sequential( # Sequential,
                        LambdaMap(lambda x: x, # ConcatTable,
                            nn.Sequential( # Sequential,
                                nn.Sequential( # Sequential,
                                    nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                    nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                ),
                                nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                nn.BatchNorm2d(1024),
                            ),
                            Lambda(lambda x: x), # Identity,
                        ),
                        LambdaReduce(lambda x,y: x+y), # CAddTable,
                        nn.ReLU(),
                    ),
                    nn.Sequential( # Sequential,
                        LambdaMap(lambda x: x, # ConcatTable,
                            nn.Sequential( # Sequential,
                                nn.Sequential( # Sequential,
                                    nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                    nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                ),
                                nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                nn.BatchNorm2d(1024),
                            ),
                            Lambda(lambda x: x), # Identity,
                        ),
                        LambdaReduce(lambda x,y: x+y), # CAddTable,
                        nn.ReLU(),
                    ),
                    nn.Sequential( # Sequential,
                        LambdaMap(lambda x: x, # ConcatTable,
                            nn.Sequential( # Sequential,
                                nn.Sequential( # Sequential,
                                    nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                    nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                ),
                                nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                nn.BatchNorm2d(1024),
                            ),
                            Lambda(lambda x: x), # Identity,
                        ),
                        LambdaReduce(lambda x,y: x+y), # CAddTable,
                        nn.ReLU(),
                    ),
                    nn.Sequential( # Sequential,
                        LambdaMap(lambda x: x, # ConcatTable,
                            nn.Sequential( # Sequential,
                                nn.Sequential( # Sequential,
                                    nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                    nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                ),
                                nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                nn.BatchNorm2d(1024),
                            ),
                            Lambda(lambda x: x), # Identity,
                        ),
                        LambdaReduce(lambda x,y: x+y), # CAddTable,
                        nn.ReLU(),
                    ),
                    nn.Sequential( # Sequential,
                        LambdaMap(lambda x: x, # ConcatTable,
                            nn.Sequential( # Sequential,
                                nn.Sequential( # Sequential,
                                    nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                    nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                ),
                                nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                nn.BatchNorm2d(1024),
                            ),
                            Lambda(lambda x: x), # Identity,
                        ),
                        LambdaReduce(lambda x,y: x+y), # CAddTable,
                        nn.ReLU(),
                    ),
                    nn.Sequential( # Sequential,
                        LambdaMap(lambda x: x, # ConcatTable,
                            nn.Sequential( # Sequential,
                                nn.Sequential( # Sequential,
                                    nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                    nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                ),
                                nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                nn.BatchNorm2d(1024),
                            ),
                            Lambda(lambda x: x), # Identity,
                        ),
                        LambdaReduce(lambda x,y: x+y), # CAddTable,
                        nn.ReLU(),
                    ),
                    nn.Sequential( # Sequential,
                        LambdaMap(lambda x: x, # ConcatTable,
                            nn.Sequential( # Sequential,
                                nn.Sequential( # Sequential,
                                    nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                    nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                ),
                                nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                nn.BatchNorm2d(1024),
                            ),
                            Lambda(lambda x: x), # Identity,
                        ),
                        LambdaReduce(lambda x,y: x+y), # CAddTable,
                        nn.ReLU(),
                    ),
                    nn.Sequential( # Sequential,
                        LambdaMap(lambda x: x, # ConcatTable,
                            nn.Sequential( # Sequential,
                                nn.Sequential( # Sequential,
                                    nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                    nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                ),
                                nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                nn.BatchNorm2d(1024),
                            ),
                            Lambda(lambda x: x), # Identity,
                        ),
                        LambdaReduce(lambda x,y: x+y), # CAddTable,
                        nn.ReLU(),
                    ),
                    nn.Sequential( # Sequential,
                        LambdaMap(lambda x: x, # ConcatTable,
                            nn.Sequential( # Sequential,
                                nn.Sequential( # Sequential,
                                    nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                    nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                ),
                                nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                nn.BatchNorm2d(1024),
                            ),
                            Lambda(lambda x: x), # Identity,
                        ),
                        LambdaReduce(lambda x,y: x+y), # CAddTable,
                        nn.ReLU(),
                    ),
                    nn.Sequential( # Sequential,
                        LambdaMap(lambda x: x, # ConcatTable,
                            nn.Sequential( # Sequential,
                                nn.Sequential( # Sequential,
                                    nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                    nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                ),
                                nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                nn.BatchNorm2d(1024),
                            ),
                            Lambda(lambda x: x), # Identity,
                        ),
                        LambdaReduce(lambda x,y: x+y), # CAddTable,
                        nn.ReLU(),
                    ),
                    nn.Sequential( # Sequential,
                        LambdaMap(lambda x: x, # ConcatTable,
                            nn.Sequential( # Sequential,
                                nn.Sequential( # Sequential,
                                    nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                    nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                ),
                                nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                nn.BatchNorm2d(1024),
                            ),
                            Lambda(lambda x: x), # Identity,
                        ),
                        LambdaReduce(lambda x,y: x+y), # CAddTable,
                        nn.ReLU(),
                    ),
                    nn.Sequential( # Sequential,
                        LambdaMap(lambda x: x, # ConcatTable,
                            nn.Sequential( # Sequential,
                                nn.Sequential( # Sequential,
                                    nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                    nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                ),
                                nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                nn.BatchNorm2d(1024),
                            ),
                            Lambda(lambda x: x), # Identity,
                        ),
                        LambdaReduce(lambda x,y: x+y), # CAddTable,
                        nn.ReLU(),
                    ),
                    nn.Sequential( # Sequential,
                        LambdaMap(lambda x: x, # ConcatTable,
                            nn.Sequential( # Sequential,
                                nn.Sequential( # Sequential,
                                    nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                    nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                                    nn.BatchNorm2d(512),
                                    nn.ReLU(),
                                ),
                                nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                                nn.BatchNorm2d(1024),
                            ),
                            Lambda(lambda x: x), # Identity,
                        ),
                        LambdaReduce(lambda x,y: x+y), # CAddTable,
                        nn.ReLU(),
                    ),
                )
        if self.stage5:
            self.C5 = nn.Sequential( # Sequential,
        nn.Sequential( # Sequential,
            LambdaMap(lambda x: x, # ConcatTable,
                nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        nn.Conv2d(1024,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                        nn.BatchNorm2d(1024),
                        nn.ReLU(),
                        nn.Conv2d(1024,1024,(3, 3),(2, 2),(1, 1),1,32,bias=False),
                        nn.BatchNorm2d(1024),
                        nn.ReLU(),
                    ),
                    nn.Conv2d(1024,2048,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(2048),
                ),
                nn.Sequential( # Sequential,
                    nn.Conv2d(1024,2048,(1, 1),(2, 2),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(2048),
                ),
            ),
            LambdaReduce(lambda x,y: x+y), # CAddTable,
            nn.ReLU(),
        ),
        nn.Sequential( # Sequential,
            LambdaMap(lambda x: x, # ConcatTable,
                nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        nn.Conv2d(2048,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                        nn.BatchNorm2d(1024),
                        nn.ReLU(),
                        nn.Conv2d(1024,1024,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                        nn.BatchNorm2d(1024),
                        nn.ReLU(),
                    ),
                    nn.Conv2d(1024,2048,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(2048),
                ),
                Lambda(lambda x: x), # Identity,
            ),
            LambdaReduce(lambda x,y: x+y), # CAddTable,
            nn.ReLU(),
        ),
        nn.Sequential( # Sequential,
            LambdaMap(lambda x: x, # ConcatTable,
                nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        nn.Conv2d(2048,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                        nn.BatchNorm2d(1024),
                        nn.ReLU(),
                        nn.Conv2d(1024,1024,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                        nn.BatchNorm2d(1024),
                        nn.ReLU(),
                    ),
                    nn.Conv2d(1024,2048,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(2048),
                ),
                Lambda(lambda x: x), # Identity,
            ),
            LambdaReduce(lambda x,y: x+y), # CAddTable,
            nn.ReLU(),
        ),
    )
        else:
            self.C5 = None

    def forward(self, x):
        x = self.C1(x)
        x = self.C2(x)
        x = self.C3(x)
        x = self.C4(x)
        x = self.C5(x)
        return x


    def stages(self):
        return [self.C1, self.C2, self.C3, self.C4, self.C5]
    
    
resnext101_32x4d_features = nn.Sequential( # Sequential,
    nn.Conv2d(3,64,(7, 7),(2, 2),(3, 3),1,1,bias=False),
    nn.BatchNorm2d(64),
    nn.ReLU(),
    nn.MaxPool2d((3, 3),(2, 2),(1, 1)),
    nn.Sequential( # Sequential,
        nn.Sequential( # Sequential,
            LambdaMap(lambda x: x, # ConcatTable,
                nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        nn.Conv2d(64,128,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                        nn.BatchNorm2d(128),
                        nn.ReLU(),
                        nn.Conv2d(128,128,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                        nn.BatchNorm2d(128),
                        nn.ReLU(),
                    ),
                    nn.Conv2d(128,256,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(256),
                ),
                nn.Sequential( # Sequential,
                    nn.Conv2d(64,256,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(256),
                ),
            ),
            LambdaReduce(lambda x,y: x+y), # CAddTable,
            nn.ReLU(),
        ),
        nn.Sequential( # Sequential,
            LambdaMap(lambda x: x, # ConcatTable,
                nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        nn.Conv2d(256,128,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                        nn.BatchNorm2d(128),
                        nn.ReLU(),
                        nn.Conv2d(128,128,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                        nn.BatchNorm2d(128),
                        nn.ReLU(),
                    ),
                    nn.Conv2d(128,256,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(256),
                ),
                Lambda(lambda x: x), # Identity,
            ),
            LambdaReduce(lambda x,y: x+y), # CAddTable,
            nn.ReLU(),
        ),
        nn.Sequential( # Sequential,
            LambdaMap(lambda x: x, # ConcatTable,
                nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        nn.Conv2d(256,128,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                        nn.BatchNorm2d(128),
                        nn.ReLU(),
                        nn.Conv2d(128,128,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                        nn.BatchNorm2d(128),
                        nn.ReLU(),
                    ),
                    nn.Conv2d(128,256,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(256),
                ),
                Lambda(lambda x: x), # Identity,
            ),
            LambdaReduce(lambda x,y: x+y), # CAddTable,
            nn.ReLU(),
        ),
    ),
    nn.Sequential( # Sequential,
        nn.Sequential( # Sequential,
            LambdaMap(lambda x: x, # ConcatTable,
                nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        nn.Conv2d(256,256,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                        nn.BatchNorm2d(256),
                        nn.ReLU(),
                        nn.Conv2d(256,256,(3, 3),(2, 2),(1, 1),1,32,bias=False),
                        nn.BatchNorm2d(256),
                        nn.ReLU(),
                    ),
                    nn.Conv2d(256,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(512),
                ),
                nn.Sequential( # Sequential,
                    nn.Conv2d(256,512,(1, 1),(2, 2),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(512),
                ),
            ),
            LambdaReduce(lambda x,y: x+y), # CAddTable,
            nn.ReLU(),
        ),
        nn.Sequential( # Sequential,
            LambdaMap(lambda x: x, # ConcatTable,
                nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        nn.Conv2d(512,256,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                        nn.BatchNorm2d(256),
                        nn.ReLU(),
                        nn.Conv2d(256,256,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                        nn.BatchNorm2d(256),
                        nn.ReLU(),
                    ),
                    nn.Conv2d(256,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(512),
                ),
                Lambda(lambda x: x), # Identity,
            ),
            LambdaReduce(lambda x,y: x+y), # CAddTable,
            nn.ReLU(),
        ),
        nn.Sequential( # Sequential,
            LambdaMap(lambda x: x, # ConcatTable,
                nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        nn.Conv2d(512,256,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                        nn.BatchNorm2d(256),
                        nn.ReLU(),
                        nn.Conv2d(256,256,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                        nn.BatchNorm2d(256),
                        nn.ReLU(),
                    ),
                    nn.Conv2d(256,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(512),
                ),
                Lambda(lambda x: x), # Identity,
            ),
            LambdaReduce(lambda x,y: x+y), # CAddTable,
            nn.ReLU(),
        ),
        nn.Sequential( # Sequential,
            LambdaMap(lambda x: x, # ConcatTable,
                nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        nn.Conv2d(512,256,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                        nn.BatchNorm2d(256),
                        nn.ReLU(),
                        nn.Conv2d(256,256,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                        nn.BatchNorm2d(256),
                        nn.ReLU(),
                    ),
                    nn.Conv2d(256,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(512),
                ),
                Lambda(lambda x: x), # Identity,
            ),
            LambdaReduce(lambda x,y: x+y), # CAddTable,
            nn.ReLU(),
        ),
    ),
    nn.Sequential( # Sequential,
        nn.Sequential( # Sequential,
            LambdaMap(lambda x: x, # ConcatTable,
                nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        nn.Conv2d(512,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                        nn.Conv2d(512,512,(3, 3),(2, 2),(1, 1),1,32,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                    ),
                    nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(1024),
                ),
                nn.Sequential( # Sequential,
                    nn.Conv2d(512,1024,(1, 1),(2, 2),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(1024),
                ),
            ),
            LambdaReduce(lambda x,y: x+y), # CAddTable,
            nn.ReLU(),
        ),
        nn.Sequential( # Sequential,
            LambdaMap(lambda x: x, # ConcatTable,
                nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                        nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                    ),
                    nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(1024),
                ),
                Lambda(lambda x: x), # Identity,
            ),
            LambdaReduce(lambda x,y: x+y), # CAddTable,
            nn.ReLU(),
        ),
        nn.Sequential( # Sequential,
            LambdaMap(lambda x: x, # ConcatTable,
                nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                        nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                    ),
                    nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(1024),
                ),
                Lambda(lambda x: x), # Identity,
            ),
            LambdaReduce(lambda x,y: x+y), # CAddTable,
            nn.ReLU(),
        ),
        nn.Sequential( # Sequential,
            LambdaMap(lambda x: x, # ConcatTable,
                nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                        nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                    ),
                    nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(1024),
                ),
                Lambda(lambda x: x), # Identity,
            ),
            LambdaReduce(lambda x,y: x+y), # CAddTable,
            nn.ReLU(),
        ),
        nn.Sequential( # Sequential,
            LambdaMap(lambda x: x, # ConcatTable,
                nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                        nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                    ),
                    nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(1024),
                ),
                Lambda(lambda x: x), # Identity,
            ),
            LambdaReduce(lambda x,y: x+y), # CAddTable,
            nn.ReLU(),
        ),
        nn.Sequential( # Sequential,
            LambdaMap(lambda x: x, # ConcatTable,
                nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                        nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                    ),
                    nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(1024),
                ),
                Lambda(lambda x: x), # Identity,
            ),
            LambdaReduce(lambda x,y: x+y), # CAddTable,
            nn.ReLU(),
        ),
        nn.Sequential( # Sequential,
            LambdaMap(lambda x: x, # ConcatTable,
                nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                        nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                    ),
                    nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(1024),
                ),
                Lambda(lambda x: x), # Identity,
            ),
            LambdaReduce(lambda x,y: x+y), # CAddTable,
            nn.ReLU(),
        ),
        nn.Sequential( # Sequential,
            LambdaMap(lambda x: x, # ConcatTable,
                nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                        nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                    ),
                    nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(1024),
                ),
                Lambda(lambda x: x), # Identity,
            ),
            LambdaReduce(lambda x,y: x+y), # CAddTable,
            nn.ReLU(),
        ),
        nn.Sequential( # Sequential,
            LambdaMap(lambda x: x, # ConcatTable,
                nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                        nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                    ),
                    nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(1024),
                ),
                Lambda(lambda x: x), # Identity,
            ),
            LambdaReduce(lambda x,y: x+y), # CAddTable,
            nn.ReLU(),
        ),
        nn.Sequential( # Sequential,
            LambdaMap(lambda x: x, # ConcatTable,
                nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                        nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                    ),
                    nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(1024),
                ),
                Lambda(lambda x: x), # Identity,
            ),
            LambdaReduce(lambda x,y: x+y), # CAddTable,
            nn.ReLU(),
        ),
        nn.Sequential( # Sequential,
            LambdaMap(lambda x: x, # ConcatTable,
                nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                        nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                    ),
                    nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(1024),
                ),
                Lambda(lambda x: x), # Identity,
            ),
            LambdaReduce(lambda x,y: x+y), # CAddTable,
            nn.ReLU(),
        ),
        nn.Sequential( # Sequential,
            LambdaMap(lambda x: x, # ConcatTable,
                nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                        nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                    ),
                    nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(1024),
                ),
                Lambda(lambda x: x), # Identity,
            ),
            LambdaReduce(lambda x,y: x+y), # CAddTable,
            nn.ReLU(),
        ),
        nn.Sequential( # Sequential,
            LambdaMap(lambda x: x, # ConcatTable,
                nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                        nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                    ),
                    nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(1024),
                ),
                Lambda(lambda x: x), # Identity,
            ),
            LambdaReduce(lambda x,y: x+y), # CAddTable,
            nn.ReLU(),
        ),
        nn.Sequential( # Sequential,
            LambdaMap(lambda x: x, # ConcatTable,
                nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                        nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                    ),
                    nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(1024),
                ),
                Lambda(lambda x: x), # Identity,
            ),
            LambdaReduce(lambda x,y: x+y), # CAddTable,
            nn.ReLU(),
        ),
        nn.Sequential( # Sequential,
            LambdaMap(lambda x: x, # ConcatTable,
                nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                        nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                    ),
                    nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(1024),
                ),
                Lambda(lambda x: x), # Identity,
            ),
            LambdaReduce(lambda x,y: x+y), # CAddTable,
            nn.ReLU(),
        ),
        nn.Sequential( # Sequential,
            LambdaMap(lambda x: x, # ConcatTable,
                nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                        nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                    ),
                    nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(1024),
                ),
                Lambda(lambda x: x), # Identity,
            ),
            LambdaReduce(lambda x,y: x+y), # CAddTable,
            nn.ReLU(),
        ),
        nn.Sequential( # Sequential,
            LambdaMap(lambda x: x, # ConcatTable,
                nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                        nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                    ),
                    nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(1024),
                ),
                Lambda(lambda x: x), # Identity,
            ),
            LambdaReduce(lambda x,y: x+y), # CAddTable,
            nn.ReLU(),
        ),
        nn.Sequential( # Sequential,
            LambdaMap(lambda x: x, # ConcatTable,
                nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                        nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                    ),
                    nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(1024),
                ),
                Lambda(lambda x: x), # Identity,
            ),
            LambdaReduce(lambda x,y: x+y), # CAddTable,
            nn.ReLU(),
        ),
        nn.Sequential( # Sequential,
            LambdaMap(lambda x: x, # ConcatTable,
                nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                        nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                    ),
                    nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(1024),
                ),
                Lambda(lambda x: x), # Identity,
            ),
            LambdaReduce(lambda x,y: x+y), # CAddTable,
            nn.ReLU(),
        ),
        nn.Sequential( # Sequential,
            LambdaMap(lambda x: x, # ConcatTable,
                nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                        nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                    ),
                    nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(1024),
                ),
                Lambda(lambda x: x), # Identity,
            ),
            LambdaReduce(lambda x,y: x+y), # CAddTable,
            nn.ReLU(),
        ),
        nn.Sequential( # Sequential,
            LambdaMap(lambda x: x, # ConcatTable,
                nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                        nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                    ),
                    nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(1024),
                ),
                Lambda(lambda x: x), # Identity,
            ),
            LambdaReduce(lambda x,y: x+y), # CAddTable,
            nn.ReLU(),
        ),
        nn.Sequential( # Sequential,
            LambdaMap(lambda x: x, # ConcatTable,
                nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                        nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                    ),
                    nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(1024),
                ),
                Lambda(lambda x: x), # Identity,
            ),
            LambdaReduce(lambda x,y: x+y), # CAddTable,
            nn.ReLU(),
        ),
        nn.Sequential( # Sequential,
            LambdaMap(lambda x: x, # ConcatTable,
                nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        nn.Conv2d(1024,512,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                        nn.Conv2d(512,512,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                        nn.BatchNorm2d(512),
                        nn.ReLU(),
                    ),
                    nn.Conv2d(512,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(1024),
                ),
                Lambda(lambda x: x), # Identity,
            ),
            LambdaReduce(lambda x,y: x+y), # CAddTable,
            nn.ReLU(),
        ),
    ),
    nn.Sequential( # Sequential,
        nn.Sequential( # Sequential,
            LambdaMap(lambda x: x, # ConcatTable,
                nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        nn.Conv2d(1024,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                        nn.BatchNorm2d(1024),
                        nn.ReLU(),
                        nn.Conv2d(1024,1024,(3, 3),(2, 2),(1, 1),1,32,bias=False),
                        nn.BatchNorm2d(1024),
                        nn.ReLU(),
                    ),
                    nn.Conv2d(1024,2048,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(2048),
                ),
                nn.Sequential( # Sequential,
                    nn.Conv2d(1024,2048,(1, 1),(2, 2),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(2048),
                ),
            ),
            LambdaReduce(lambda x,y: x+y), # CAddTable,
            nn.ReLU(),
        ),
        nn.Sequential( # Sequential,
            LambdaMap(lambda x: x, # ConcatTable,
                nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        nn.Conv2d(2048,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                        nn.BatchNorm2d(1024),
                        nn.ReLU(),
                        nn.Conv2d(1024,1024,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                        nn.BatchNorm2d(1024),
                        nn.ReLU(),
                    ),
                    nn.Conv2d(1024,2048,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(2048),
                ),
                Lambda(lambda x: x), # Identity,
            ),
            LambdaReduce(lambda x,y: x+y), # CAddTable,
            nn.ReLU(),
        ),
        nn.Sequential( # Sequential,
            LambdaMap(lambda x: x, # ConcatTable,
                nn.Sequential( # Sequential,
                    nn.Sequential( # Sequential,
                        nn.Conv2d(2048,1024,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                        nn.BatchNorm2d(1024),
                        nn.ReLU(),
                        nn.Conv2d(1024,1024,(3, 3),(1, 1),(1, 1),1,32,bias=False),
                        nn.BatchNorm2d(1024),
                        nn.ReLU(),
                    ),
                    nn.Conv2d(1024,2048,(1, 1),(1, 1),(0, 0),1,1,bias=False),
                    nn.BatchNorm2d(2048),
                ),
                Lambda(lambda x: x), # Identity,
            ),
            LambdaReduce(lambda x,y: x+y), # CAddTable,
            nn.ReLU(),
        ),
    )
)